# Config file for automatic testing at travis-ci.org
#

language: python

python:
        - "3.6"

install:
        - pip install pipenv
        - pipenv install --dev
        - pipenv run pip install coveralls
script: 
        - pipenv run pytest
        - pipenv run coveralls
