# Config file for automatic testing at travis-ci.org
#

language: python

python:
        - "3.6"
        - "3.5"

install:
        - pip install pipenv
        - pipenv install --dev
script: 
        - pipenv run pytest
        - pipenv run coveralls
