# Generated by Django 2.0.4 on 2018-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20180410_1748")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="A few words about you.",
                max_length=255,
                null=True,
                verbose_name="Bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="homepage_url",
            field=models.URLField(
                blank=True,
                help_text="Your home on the web.",
                null=True,
                verbose_name="Homepage",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="🎶 What's your name, son? ALEXANDER HAMILTON",
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
