# Generated by Django 2.0.4 on 2018-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20180413_2215")]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="name", new_name="display_name"
        )
    ]
