# Generated by Django 2.0.4 on 2018-04-19 17:45

from django.db import migrations
import django.utils.timezone
import fiction_outlines.models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20180419_0630")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="modified",
            field=fiction_outlines.models.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False
            ),
        )
    ]
